# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 542)
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.simple_page = QtWidgets.QWidget()
        self.simple_page.setObjectName("simple_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.simple_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.screen = QtWidgets.QLabel(self.simple_page)
        self.screen.setMinimumSize(QtCore.QSize(360, 50))
        self.screen.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.screen.setText("")
        self.screen.setObjectName("screen")
        self.verticalLayout_2.addWidget(self.screen)
        self.Buttons = QtWidgets.QWidget(self.simple_page)
        self.Buttons.setMinimumSize(QtCore.QSize(360, 390))
        self.Buttons.setObjectName("Buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Buttons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_8 = QtWidgets.QWidget(self.Buttons)
        self.widget_8.setMinimumSize(QtCore.QSize(75, 0))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.back_bt = QtWidgets.QPushButton(self.widget_8)
        self.back_bt.setMinimumSize(QtCore.QSize(70, 50))
        self.back_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #E2E1DE;\n"
"border-radius: 7px;\n"
"")
        self.back_bt.setObjectName("back_bt")
        self.verticalLayout_3.addWidget(self.back_bt)
        self.button1 = QtWidgets.QPushButton(self.widget_8)
        self.button1.setMinimumSize(QtCore.QSize(70, 70))
        self.button1.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button1.setObjectName("button1")
        self.verticalLayout_3.addWidget(self.button1)
        self.button4 = QtWidgets.QPushButton(self.widget_8)
        self.button4.setMinimumSize(QtCore.QSize(70, 70))
        self.button4.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button4.setObjectName("button4")
        self.verticalLayout_3.addWidget(self.button4)
        self.button7 = QtWidgets.QPushButton(self.widget_8)
        self.button7.setMinimumSize(QtCore.QSize(70, 70))
        self.button7.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button7.setObjectName("button7")
        self.verticalLayout_3.addWidget(self.button7)
        self.button_clear = QtWidgets.QPushButton(self.widget_8)
        self.button_clear.setMinimumSize(QtCore.QSize(70, 70))
        self.button_clear.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(150, 0, 0);\n"
" border-radius: 7px")
        self.button_clear.setObjectName("button_clear")
        self.verticalLayout_3.addWidget(self.button_clear)
        self.horizontalLayout_2.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.Buttons)
        self.widget_9.setMinimumSize(QtCore.QSize(75, 0))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.forward_bt = QtWidgets.QPushButton(self.widget_9)
        self.forward_bt.setMinimumSize(QtCore.QSize(70, 50))
        self.forward_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #E2E1DE;\n"
"border-radius: 7px;\n"
"")
        self.forward_bt.setObjectName("forward_bt")
        self.verticalLayout_4.addWidget(self.forward_bt)
        self.button2 = QtWidgets.QPushButton(self.widget_9)
        self.button2.setMinimumSize(QtCore.QSize(70, 70))
        self.button2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px\n"
"\n"
"\n"
"")
        self.button2.setObjectName("button2")
        self.verticalLayout_4.addWidget(self.button2)
        self.button5 = QtWidgets.QPushButton(self.widget_9)
        self.button5.setMinimumSize(QtCore.QSize(70, 70))
        self.button5.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px\n"
"")
        self.button5.setObjectName("button5")
        self.verticalLayout_4.addWidget(self.button5)
        self.button8 = QtWidgets.QPushButton(self.widget_9)
        self.button8.setMinimumSize(QtCore.QSize(70, 70))
        self.button8.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button8.setObjectName("button8")
        self.verticalLayout_4.addWidget(self.button8)
        self.button0 = QtWidgets.QPushButton(self.widget_9)
        self.button0.setMinimumSize(QtCore.QSize(70, 70))
        self.button0.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button0.setObjectName("button0")
        self.verticalLayout_4.addWidget(self.button0)
        self.horizontalLayout_2.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.Buttons)
        self.widget_10.setMinimumSize(QtCore.QSize(75, 0))
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ac_bt = QtWidgets.QPushButton(self.widget_10)
        self.ac_bt.setMinimumSize(QtCore.QSize(70, 50))
        self.ac_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(150, 0, 0);\n"
"border-radius: 7px;\n"
"")
        self.ac_bt.setObjectName("ac_bt")
        self.verticalLayout_5.addWidget(self.ac_bt)
        self.button3 = QtWidgets.QPushButton(self.widget_10)
        self.button3.setMinimumSize(QtCore.QSize(70, 70))
        self.button3.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button3.setObjectName("button3")
        self.verticalLayout_5.addWidget(self.button3)
        self.button6 = QtWidgets.QPushButton(self.widget_10)
        self.button6.setMinimumSize(QtCore.QSize(70, 70))
        self.button6.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button6.setObjectName("button6")
        self.verticalLayout_5.addWidget(self.button6)
        self.button9 = QtWidgets.QPushButton(self.widget_10)
        self.button9.setMinimumSize(QtCore.QSize(70, 70))
        self.button9.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button9.setObjectName("button9")
        self.verticalLayout_5.addWidget(self.button9)
        self.button_equal = QtWidgets.QPushButton(self.widget_10)
        self.button_equal.setMinimumSize(QtCore.QSize(70, 70))
        self.button_equal.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #4E9C79;\n"
" border-radius: 7px")
        self.button_equal.setObjectName("button_equal")
        self.verticalLayout_5.addWidget(self.button_equal)
        self.horizontalLayout_2.addWidget(self.widget_10)
        self.widget_4 = QtWidgets.QWidget(self.Buttons)
        self.widget_4.setMinimumSize(QtCore.QSize(75, 0))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ans_bt = QtWidgets.QPushButton(self.widget_4)
        self.ans_bt.setMinimumSize(QtCore.QSize(70, 50))
        self.ans_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #FFCA63;\n"
" border-radius: 7px")
        self.ans_bt.setObjectName("ans_bt")
        self.verticalLayout.addWidget(self.ans_bt)
        self.button_plus = QtWidgets.QPushButton(self.widget_4)
        self.button_plus.setMinimumSize(QtCore.QSize(70, 70))
        self.button_plus.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(6, 70, 1);\n"
" border-radius: 7px;")
        self.button_plus.setObjectName("button_plus")
        self.verticalLayout.addWidget(self.button_plus)
        self.button_minus = QtWidgets.QPushButton(self.widget_4)
        self.button_minus.setMinimumSize(QtCore.QSize(70, 70))
        self.button_minus.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(6, 70, 1);\n"
" border-radius: 7px;")
        self.button_minus.setObjectName("button_minus")
        self.verticalLayout.addWidget(self.button_minus)
        self.button_multi = QtWidgets.QPushButton(self.widget_4)
        self.button_multi.setMinimumSize(QtCore.QSize(70, 70))
        self.button_multi.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(6, 70, 1);\n"
" border-radius: 7px;")
        self.button_multi.setObjectName("button_multi")
        self.verticalLayout.addWidget(self.button_multi)
        self.button_division = QtWidgets.QPushButton(self.widget_4)
        self.button_division.setMinimumSize(QtCore.QSize(70, 70))
        self.button_division.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(6, 70, 1);\n"
" border-radius: 7px;")
        self.button_division.setObjectName("button_division")
        self.verticalLayout.addWidget(self.button_division)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.verticalLayout_2.addWidget(self.Buttons)
        self.stackedWidget.addWidget(self.simple_page)
        self.advanced_page = QtWidgets.QWidget()
        self.advanced_page.setObjectName("advanced_page")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.advanced_page)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.screen_2 = QtWidgets.QLabel(self.advanced_page)
        self.screen_2.setMinimumSize(QtCore.QSize(360, 50))
        self.screen_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.screen_2.setText("")
        self.screen_2.setObjectName("screen_2")
        self.verticalLayout_13.addWidget(self.screen_2)
        self.Buttons_2 = QtWidgets.QWidget(self.advanced_page)
        self.Buttons_2.setMinimumSize(QtCore.QSize(360, 390))
        self.Buttons_2.setObjectName("Buttons_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Buttons_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_11 = QtWidgets.QWidget(self.Buttons_2)
        self.widget_11.setMinimumSize(QtCore.QSize(75, 0))
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.back_bt_2 = QtWidgets.QPushButton(self.widget_11)
        self.back_bt_2.setMinimumSize(QtCore.QSize(70, 50))
        self.back_bt_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #E2E1DE;\n"
"border-radius: 7px;\n"
"")
        self.back_bt_2.setObjectName("back_bt_2")
        self.verticalLayout_7.addWidget(self.back_bt_2)
        self.button1_2 = QtWidgets.QPushButton(self.widget_11)
        self.button1_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button1_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button1_2.setObjectName("button1_2")
        self.verticalLayout_7.addWidget(self.button1_2)
        self.button4_2 = QtWidgets.QPushButton(self.widget_11)
        self.button4_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button4_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button4_2.setObjectName("button4_2")
        self.verticalLayout_7.addWidget(self.button4_2)
        self.button7_2 = QtWidgets.QPushButton(self.widget_11)
        self.button7_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button7_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button7_2.setObjectName("button7_2")
        self.verticalLayout_7.addWidget(self.button7_2)
        self.button_clear_2 = QtWidgets.QPushButton(self.widget_11)
        self.button_clear_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button_clear_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(150, 0, 0);\n"
" border-radius: 7px")
        self.button_clear_2.setObjectName("button_clear_2")
        self.verticalLayout_7.addWidget(self.button_clear_2)
        self.horizontalLayout_3.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.Buttons_2)
        self.widget_12.setMinimumSize(QtCore.QSize(75, 0))
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.forward_bt_2 = QtWidgets.QPushButton(self.widget_12)
        self.forward_bt_2.setMinimumSize(QtCore.QSize(70, 50))
        self.forward_bt_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #E2E1DE;\n"
"border-radius: 7px;\n"
"")
        self.forward_bt_2.setObjectName("forward_bt_2")
        self.verticalLayout_8.addWidget(self.forward_bt_2)
        self.button2_2 = QtWidgets.QPushButton(self.widget_12)
        self.button2_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button2_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px\n"
"\n"
"\n"
"")
        self.button2_2.setObjectName("button2_2")
        self.verticalLayout_8.addWidget(self.button2_2)
        self.button5_2 = QtWidgets.QPushButton(self.widget_12)
        self.button5_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button5_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px\n"
"")
        self.button5_2.setObjectName("button5_2")
        self.verticalLayout_8.addWidget(self.button5_2)
        self.button8_2 = QtWidgets.QPushButton(self.widget_12)
        self.button8_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button8_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button8_2.setObjectName("button8_2")
        self.verticalLayout_8.addWidget(self.button8_2)
        self.button0_2 = QtWidgets.QPushButton(self.widget_12)
        self.button0_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button0_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button0_2.setObjectName("button0_2")
        self.verticalLayout_8.addWidget(self.button0_2)
        self.horizontalLayout_3.addWidget(self.widget_12)
        self.widget_13 = QtWidgets.QWidget(self.Buttons_2)
        self.widget_13.setMinimumSize(QtCore.QSize(75, 0))
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.ac_bt_2 = QtWidgets.QPushButton(self.widget_13)
        self.ac_bt_2.setMinimumSize(QtCore.QSize(70, 50))
        self.ac_bt_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(150, 0, 0);\n"
"border-radius: 7px;\n"
"")
        self.ac_bt_2.setObjectName("ac_bt_2")
        self.verticalLayout_9.addWidget(self.ac_bt_2)
        self.button3_2 = QtWidgets.QPushButton(self.widget_13)
        self.button3_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button3_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button3_2.setObjectName("button3_2")
        self.verticalLayout_9.addWidget(self.button3_2)
        self.button6_2 = QtWidgets.QPushButton(self.widget_13)
        self.button6_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button6_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button6_2.setObjectName("button6_2")
        self.verticalLayout_9.addWidget(self.button6_2)
        self.button9_2 = QtWidgets.QPushButton(self.widget_13)
        self.button9_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button9_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #2F96F4;\n"
" border-radius: 7px")
        self.button9_2.setObjectName("button9_2")
        self.verticalLayout_9.addWidget(self.button9_2)
        self.button_equal_2 = QtWidgets.QPushButton(self.widget_13)
        self.button_equal_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button_equal_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #4E9C79;\n"
" border-radius: 7px")
        self.button_equal_2.setObjectName("button_equal_2")
        self.verticalLayout_9.addWidget(self.button_equal_2)
        self.horizontalLayout_3.addWidget(self.widget_13)
        self.widget_5 = QtWidgets.QWidget(self.Buttons_2)
        self.widget_5.setMinimumSize(QtCore.QSize(75, 0))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.ans_bt_2 = QtWidgets.QPushButton(self.widget_5)
        self.ans_bt_2.setMinimumSize(QtCore.QSize(70, 50))
        self.ans_bt_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #FFCA63;\n"
" border-radius: 7px")
        self.ans_bt_2.setObjectName("ans_bt_2")
        self.verticalLayout_10.addWidget(self.ans_bt_2)
        self.button_plus_2 = QtWidgets.QPushButton(self.widget_5)
        self.button_plus_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button_plus_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(6, 70, 1);\n"
" border-radius: 7px;")
        self.button_plus_2.setObjectName("button_plus_2")
        self.verticalLayout_10.addWidget(self.button_plus_2)
        self.button_minus_2 = QtWidgets.QPushButton(self.widget_5)
        self.button_minus_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button_minus_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(6, 70, 1);\n"
" border-radius: 7px;")
        self.button_minus_2.setObjectName("button_minus_2")
        self.verticalLayout_10.addWidget(self.button_minus_2)
        self.button_multi_2 = QtWidgets.QPushButton(self.widget_5)
        self.button_multi_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button_multi_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(6, 70, 1);\n"
" border-radius: 7px;")
        self.button_multi_2.setObjectName("button_multi_2")
        self.verticalLayout_10.addWidget(self.button_multi_2)
        self.button_division_2 = QtWidgets.QPushButton(self.widget_5)
        self.button_division_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button_division_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(6, 70, 1);\n"
" border-radius: 7px;")
        self.button_division_2.setObjectName("button_division_2")
        self.verticalLayout_10.addWidget(self.button_division_2)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.widget_2 = QtWidgets.QWidget(self.Buttons_2)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.blank_bt = QtWidgets.QPushButton(self.widget_2)
        self.blank_bt.setMinimumSize(QtCore.QSize(70, 50))
        self.blank_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #ffffff;\n"
" border-radius: 7px;")
        self.blank_bt.setText("")
        self.blank_bt.setObjectName("blank_bt")
        self.verticalLayout_11.addWidget(self.blank_bt)
        self.left_pr_bt = QtWidgets.QPushButton(self.widget_2)
        self.left_pr_bt.setMinimumSize(QtCore.QSize(70, 70))
        self.left_pr_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #FF9852;\n"
" border-radius: 7px;")
        self.left_pr_bt.setObjectName("left_pr_bt")
        self.verticalLayout_11.addWidget(self.left_pr_bt)
        self.root_bt = QtWidgets.QPushButton(self.widget_2)
        self.root_bt.setMinimumSize(QtCore.QSize(70, 70))
        self.root_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #FF9852;\n"
" border-radius: 7px;")
        self.root_bt.setObjectName("root_bt")
        self.verticalLayout_11.addWidget(self.root_bt)
        self.exp_bt = QtWidgets.QPushButton(self.widget_2)
        self.exp_bt.setMinimumSize(QtCore.QSize(70, 70))
        self.exp_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #FF9852;\n"
" border-radius: 7px;")
        self.exp_bt.setObjectName("exp_bt")
        self.verticalLayout_11.addWidget(self.exp_bt)
        self.factorial_bt = QtWidgets.QPushButton(self.widget_2)
        self.factorial_bt.setMinimumSize(QtCore.QSize(70, 70))
        self.factorial_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #FF9852;\n"
" border-radius: 7px;")
        self.factorial_bt.setObjectName("factorial_bt")
        self.verticalLayout_11.addWidget(self.factorial_bt)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.Buttons_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.blank_bt_2 = QtWidgets.QPushButton(self.widget_3)
        self.blank_bt_2.setMinimumSize(QtCore.QSize(70, 50))
        self.blank_bt_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #ffffff;\n"
" border-radius: 7px;")
        self.blank_bt_2.setText("")
        self.blank_bt_2.setObjectName("blank_bt_2")
        self.verticalLayout_12.addWidget(self.blank_bt_2)
        self.right_pr_bt = QtWidgets.QPushButton(self.widget_3)
        self.right_pr_bt.setMinimumSize(QtCore.QSize(70, 70))
        self.right_pr_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #FF9852;\n"
" border-radius: 7px;")
        self.right_pr_bt.setObjectName("right_pr_bt")
        self.verticalLayout_12.addWidget(self.right_pr_bt)
        self.sin_bt = QtWidgets.QPushButton(self.widget_3)
        self.sin_bt.setMinimumSize(QtCore.QSize(70, 70))
        self.sin_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #FF9852;\n"
" border-radius: 7px;")
        self.sin_bt.setObjectName("sin_bt")
        self.verticalLayout_12.addWidget(self.sin_bt)
        self.cos_bt = QtWidgets.QPushButton(self.widget_3)
        self.cos_bt.setMinimumSize(QtCore.QSize(70, 70))
        self.cos_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #FF9852;\n"
" border-radius: 7px;")
        self.cos_bt.setObjectName("cos_bt")
        self.verticalLayout_12.addWidget(self.cos_bt)
        self.tan_bt = QtWidgets.QPushButton(self.widget_3)
        self.tan_bt.setMinimumSize(QtCore.QSize(70, 70))
        self.tan_bt.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: #FF9852;\n"
" border-radius: 7px;")
        self.tan_bt.setObjectName("tan_bt")
        self.verticalLayout_12.addWidget(self.tan_bt)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.verticalLayout_13.addWidget(self.Buttons_2)
        self.stackedWidget.addWidget(self.advanced_page)
        self.history_page = QtWidgets.QWidget()
        self.history_page.setObjectName("history_page")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.history_page)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.history = QtWidgets.QLabel(self.history_page)
        self.history.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.history.setText("")
        self.history.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.history.setObjectName("history")
        self.horizontalLayout_4.addWidget(self.history)
        self.stackedWidget.addWidget(self.history_page)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.simple_bt = QtWidgets.QPushButton(self.widget)
        self.simple_bt.setMinimumSize(QtCore.QSize(0, 50))
        self.simple_bt.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: #6126AE;\n"
" border-radius: 5px")
        self.simple_bt.setObjectName("simple_bt")
        self.horizontalLayout.addWidget(self.simple_bt)
        self.advanced_bt = QtWidgets.QPushButton(self.widget)
        self.advanced_bt.setMinimumSize(QtCore.QSize(0, 50))
        self.advanced_bt.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: #6126AE;\n"
" border-radius: 5px")
        self.advanced_bt.setObjectName("advanced_bt")
        self.horizontalLayout.addWidget(self.advanced_bt)
        self.history_bt = QtWidgets.QPushButton(self.widget)
        self.history_bt.setMinimumSize(QtCore.QSize(0, 50))
        self.history_bt.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: #6126AE;\n"
" border-radius: 5px")
        self.history_bt.setFlat(False)
        self.history_bt.setObjectName("history_bt")
        self.horizontalLayout.addWidget(self.history_bt)
        self.verticalLayout_6.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_bt.setText(_translate("MainWindow", "←"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button4.setText(_translate("MainWindow", "4"))
        self.button7.setText(_translate("MainWindow", "7"))
        self.button_clear.setText(_translate("MainWindow", "C"))
        self.forward_bt.setText(_translate("MainWindow", "→"))
        self.button2.setText(_translate("MainWindow", "2"))
        self.button5.setText(_translate("MainWindow", "5"))
        self.button8.setText(_translate("MainWindow", "8"))
        self.button0.setText(_translate("MainWindow", "0"))
        self.ac_bt.setText(_translate("MainWindow", "AC"))
        self.button3.setText(_translate("MainWindow", "3"))
        self.button6.setText(_translate("MainWindow", "6"))
        self.button9.setText(_translate("MainWindow", "9"))
        self.button_equal.setText(_translate("MainWindow", "="))
        self.ans_bt.setText(_translate("MainWindow", "ANS"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_multi.setText(_translate("MainWindow", "*"))
        self.button_division.setText(_translate("MainWindow", "/"))
        self.back_bt_2.setText(_translate("MainWindow", "←"))
        self.button1_2.setText(_translate("MainWindow", "1"))
        self.button4_2.setText(_translate("MainWindow", "4"))
        self.button7_2.setText(_translate("MainWindow", "7"))
        self.button_clear_2.setText(_translate("MainWindow", "C"))
        self.forward_bt_2.setText(_translate("MainWindow", "→"))
        self.button2_2.setText(_translate("MainWindow", "2"))
        self.button5_2.setText(_translate("MainWindow", "5"))
        self.button8_2.setText(_translate("MainWindow", "8"))
        self.button0_2.setText(_translate("MainWindow", "0"))
        self.ac_bt_2.setText(_translate("MainWindow", "AC"))
        self.button3_2.setText(_translate("MainWindow", "3"))
        self.button6_2.setText(_translate("MainWindow", "6"))
        self.button9_2.setText(_translate("MainWindow", "9"))
        self.button_equal_2.setText(_translate("MainWindow", "="))
        self.ans_bt_2.setText(_translate("MainWindow", "ANS"))
        self.button_plus_2.setText(_translate("MainWindow", "+"))
        self.button_minus_2.setText(_translate("MainWindow", "-"))
        self.button_multi_2.setText(_translate("MainWindow", "*"))
        self.button_division_2.setText(_translate("MainWindow", "/"))
        self.left_pr_bt.setText(_translate("MainWindow", "("))
        self.root_bt.setText(_translate("MainWindow", "√"))
        self.exp_bt.setText(_translate("MainWindow", "**"))
        self.factorial_bt.setText(_translate("MainWindow", "x!"))
        self.right_pr_bt.setText(_translate("MainWindow", ")"))
        self.sin_bt.setText(_translate("MainWindow", "sin"))
        self.cos_bt.setText(_translate("MainWindow", "cos"))
        self.tan_bt.setText(_translate("MainWindow", "tan"))
        self.simple_bt.setText(_translate("MainWindow", "Simple"))
        self.advanced_bt.setText(_translate("MainWindow", "Advanced"))
        self.history_bt.setText(_translate("MainWindow", "History"))
