# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1308, 1373)
        MainWindow.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("border: 3px solid gray;\n"
"border-radius: 20px;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image = QtWidgets.QLabel(self.widget)
        self.image.setMinimumSize(QtCore.QSize(1280, 840))
        self.image.setStyleSheet("border: 0px;\n"
"background-color: \"transparent\";")
        self.image.setText("")
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(1000, 500))
        self.widget_2.setMaximumSize(QtCore.QSize(1200, 550))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.camera_bt = QtWidgets.QPushButton(self.widget_2)
        self.camera_bt.setMinimumSize(QtCore.QSize(200, 120))
        self.camera_bt.setStyleSheet("background-color: rgb(14, 14, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid white;\n"
"border-radius: 20px;")
        self.camera_bt.setObjectName("camera_bt")
        self.verticalLayout_2.addWidget(self.camera_bt)
        self.video_bt = QtWidgets.QPushButton(self.widget_2)
        self.video_bt.setMinimumSize(QtCore.QSize(200, 120))
        self.video_bt.setStyleSheet("background-color: rgb(14, 14, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid white;\n"
"border-radius: 20px;")
        self.video_bt.setObjectName("video_bt")
        self.verticalLayout_2.addWidget(self.video_bt)
        self.stop_bt = QtWidgets.QPushButton(self.widget_2)
        self.stop_bt.setMinimumSize(QtCore.QSize(200, 120))
        self.stop_bt.setStyleSheet("background-color: rgb(14, 14, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid white;\n"
"border-radius: 20px;")
        self.stop_bt.setObjectName("stop_bt")
        self.verticalLayout_2.addWidget(self.stop_bt)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.camera_bt.setText(_translate("MainWindow", "Open camera"))
        self.video_bt.setText(_translate("MainWindow", "Show Video"))
        self.stop_bt.setText(_translate("MainWindow", "Stop"))
