# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1448, 1693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("border: 3px solid gray;\n"
"border-radius: 20px;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image = QtWidgets.QLabel(self.widget)
        self.image.setMinimumSize(QtCore.QSize(1420, 1360))
        self.image.setStyleSheet("border: 0px;\n"
"background-color: \"transparent\";")
        self.image.setText("")
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(1000, 300))
        self.widget_2.setMaximumSize(QtCore.QSize(1400, 400))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.show_bt = QtWidgets.QPushButton(self.widget_2)
        self.show_bt.setMinimumSize(QtCore.QSize(200, 120))
        self.show_bt.setStyleSheet("background-color: rgb(14, 14, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid white;\n"
"border-radius: 20px;")
        self.show_bt.setObjectName("show_bt")
        self.verticalLayout_3.addWidget(self.show_bt)
        self.clear_bt = QtWidgets.QPushButton(self.widget_2)
        self.clear_bt.setMinimumSize(QtCore.QSize(100, 120))
        self.clear_bt.setStyleSheet("background-color: rgb(14, 14, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid white;\n"
"border-radius: 20px;")
        self.clear_bt.setObjectName("clear_bt")
        self.verticalLayout_3.addWidget(self.clear_bt)
        self.verticalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.show_bt.setText(_translate("MainWindow", "Show"))
        self.clear_bt.setText(_translate("MainWindow", "Clear"))
